name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: "swift:5.6"
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: |
        swift --version
        swift package --version
        swift test -v
