name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:"5.6"
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        swift --version
        swift package --version
        swift build -v

  deploy-github-pages:
    runs-on: ubuntu-latest
    container: swift:"5.6"
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: make setup
    - name: Deploy to GitHub Pages
      run: make deploy
